### ISSUE TITLE
Adicionar dependência do Swagger

### ISSUE THREAD

**Issue by fawnbr** [THE-TRIADE/backend#18]

**Comment by fawnbr** [comment]
```xml
		<!-- OPENAPI (SWAGGER) -->
		<!-- https://mvnrepository.com/artifact/org.springdoc/springdoc-openapi-webflux-core -->
		<dependency>
			<groupId>org.springdoc</groupId>
			<artifactId>springdoc-openapi-webflux-core</artifactId>
			<version>1.6.6</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.springdoc/springdoc-openapi-webflux-ui -->
		<dependency>
			<groupId>org.springdoc</groupId>
			<artifactId>springdoc-openapi-webflux-ui</artifactId>
			<version>1.6.6</version>
		</dependency>
```

```yaml
# Swagger
springdoc:
  api-docs:
    path: /swagger-doc/familyroutine/v3/api-docs/familyroutine
  webjars:
    prefix: /familyroutine
  swagger-ui:
    path: /swagger-doc/familyroutine
```
